apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  name: ace-server1
  namespace: cp4i-api
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProductionFREE
  replicas: 1
  template:
    spec:
      containers:
        - name: runtime
          resources:
            requests:
              cpu: 300m
              memory: 368Mi
  version: '12.0'
  barURL:
    - https://github.com/bmanoj27/ace-cicd/raw/refs/heads/main/HttpEchoApp.bar
  configurations:
    - github
  forceFlowsHTTPS:
    enabled: true